baseURL = 'https://www.petermcconnell.com/'
languageCode = 'en-us'
title = 'Peter McConnell :: systems engineering manager'

enableRobotsTXT = true

# theme
baseurl = "/"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
paginate = 5

[outputs]
  home = ["HTML", "RSS"]

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "PeteMcConnell_"
  site = "PeteMcConnell_"

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    title = "Peter McConnell :: Ponderings from a Linux Systems engineer"
    subtitle = "A software focused blog for those interested in linux systems and performance"
    owner = "Peter McConnell"
    keywords = "software,engineering,linux,python,sre,peter,mcconnell,pemcconnell"
    copyright = "&copy; Peter McConnell 2023"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Peter McConnell"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "/skills"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
  [languages.fr]
    languageName = "Français"
    title = "Peter McConnell :: Réflexions d'un ingénieur système Linux"
    subtitle = "Un blog axé sur les logiciels pour ceux qui s'intéressent aux systèmes Linux et à leurs performances"
    owner = "Peter McConnell"
    keywords = "logiciel,programmation,linux,python,sre,peter,mcconnell,pemcconnell"
    copyright = "&copy; Peter McConnell 2023"
    menuMore = "Afficher plus"
    readMore = "Lire la suite"
    readOtherPosts = "Lire d'autres articles"
    newerPosts = "Articles plus récents"
    olderPosts = "Articles plus anciens"
    missingContentMessage = "Page introuvable..."
    missingBackButtonLabel = "Retour à la page d'accueil"

    [languages.fr.params.logo]
      logoText = "Peter McConnell"
      logoHomeLink = "/fr/"

    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "about"
        name = "Environ"
        url = "/fr/about"
      [[languages.fr.menu.main]]
        identifier = "skills"
        name = "Compétences"
        url = "/fr/skills"
      [[languages.fr.menu.main]]
        identifier = "showcase"
        name = "Vitrine"
        url = "/fr/showcase"
  [languages.pt]
    languageName = "Português"
    title = "Peter McConnell :: Ponderações de um engenheiro de sistemas Linux"
    subtitle = "Um blog focado em software para os interessados em sistemas Linux e desempenho"
    owner = "Peter McConnell"
    keywords = "software,programação,linux,python,sre,peter,mcconnell,pemcconnell"
    copyright = "&copy; Peter McConnell 2023"
    menuMore = "Mostre mais"
    readMore = "Consulte para mais informações"
    readOtherPosts = "Leia outras postagens"
    newerPosts = "Postagens mais recentes"
    olderPosts = "Posts mais antigos"
    missingContentMessage = "página não encontrada..."
    missingBackButtonLabel = "Voltar à página inicial"

    [languages.pt.params.logo]
      logoText = "Peter McConnell"
      logoHomeLink = "/pt/"

    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/pt/about"
      [[languages.pt.menu.main]]
        identifier = "skills"
        name = "Habilidades"
        url = "/pt/skills"
      [[languages.pt.menu.main]]
        identifier = "showcase"
        name = "Mostruário"
        url = "/pt/showcase"
  [languages.es]
    languageName = "Española"
    title = "Peter McConnell :: Reflexiones de un ingeniero de sistemas Linux"
    subtitle = "Un blog centrado en el software para aquellos interesados en los sistemas y el rendimiento de Linux"
    owner = "Peter McConnell"
    keywords = "software,programación,linux,python,sre,peter,mcconnell,pemcconnell"
    copyright = "&copy; Peter McConnell 2023"
    menuMore = "Mostrar más"
    readMore = "Lee mas"
    readOtherPosts = "Leer otras publicaciones"
    newerPosts = "las publicaciones más nuevas"
    olderPosts = "Publicaciones más antiguas"
    missingContentMessage = "Página no encontrada..."
    missingBackButtonLabel = "Volver a la página de inicio"

    [languages.es.params.logo]
      logoText = "Peter McConnell"
      logoHomeLink = "/es/"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/es/about"
      [[languages.es.menu.main]]
        identifier = "skills"
        name = "Habilidades"
        url = "/es/skills"
      [[languages.es.menu.main]]
        identifier = "showcase"
        name = "Escaparate"
        url = "/es/showcase"

[module]
  replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
